### ISSUE TITLE
Guidelines for creating issues

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/dev-docs#11]
## Introduction

GitHub issues are the main information conduit for software development, internally and externally. As such it is very important that they are fit for this purpose.

## Resources

First up, some resources for ideas and background:

https://wiredcraft.com/blog/how-we-write-our-github-issues/
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md
https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f
https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/project_management/write-good-issues/

## Proposed guidelines

Not gonna lie, I just asked a LLM for guidelines for a good GitHub issue based on the above resources, and these all seem pretty reasonable:

1. **Be clear and concise**: Explain the problem or issue in as few words as possible. Be specific and provide all relevant details.
2. **Short and descriptive title**: The title is the most visible part of your issue, you want it short and to the point.
3. **Provide context:** Explain why the problem is important and how it affects you or others. Provide any relevant background information that will help others understand the issue.
4. **Provide a way to reproduce the issue:** Clearly outline the steps needed to reproduce the issue, and provide any relevant logs or error messages. Ideally include a [Minimal Complete Verifiable Example (MCVE)](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
5. **Include relevant files or code:** If the issue is related to a specific file or piece of code, include it in the issue description.
6. **Provide a desired outcome:** Explain what you expect to happen when the issue is resolved.
7. **Use proper grammar and spelling:** Poor grammar and spelling can make it difficult for others to understand your issue, so be sure to proofread your message before submitting it.
8. **Be respectful:** Treat others as you would like to be treated. Be respectful and polite in your interactions with others, even if you are frustrated or upset.
9. **Use relevant labels:** Use relevant labels to help others quickly identify the type of issue you are reporting.
10. **Provide updates:** Keep the issue updated as you continue to work on it, and provide any additional information that may be helpful to others.

By following these guidelines, you can help ensure that your GitHub issue is clear, concise, and easy for others to understand and work on.

## Anti-patterns

I don't want to issue-shame anyone, but empty issues are an anti-pattern. If you have time to create the issue, you can spend a minute putting in some descriptive text in the body of the issue. Not only is it good practice, an empty issue sends a message, and it isn't a good one.

It is my opinion that pull requests should always be associated with an issue. The issue is where you outline the problem, discuss approaches and background. The pull request is where the codebase is updated to fix the related issue, including detailed code review. I am happy to include this as a guideline, just not sure where to put it: might be more appropriate in the pull requests section.

Edited 9/6/2023: Removed redundancy and include MCVE text.

**Comment by dougiesquire** [comment]
> I don't want to issue-shame anyone, but empty issues are an anti-pattern

I feel attacked. But I agree.

Also Minimal Complete Verifiable Examples are pretty important for bug reports. This is a nice blog post about them: http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by aidanheerdegen** [comment]
Given there has been time to comment/complain, I'm going to add this and close the issue.
