### ISSUE TITLE
ACCESS-NRI Python package branding / naming conventions

### ISSUE THREAD

**Issue by headmetal** [ACCESS-NRI/dev-docs#2]
Building on the [existing draft package naming conventions](https://github.com/ACCESS-NRI/dev-docs/wiki/Code-guidelines#package-names), do we / can we ignite some conversation around 'branding' conventions?

As a simple example - do we want to decide upon and add some kind of prefix/suffix convention to all Python packages in order to create both continuity between and recognition for ACCESS-NRI software releases? This could potentially look something like:
* `ANRI_package`
* `package_ANRI`
* `ANRIpackage`
* `packageANRI`

etc etc

**Comment by aidanheerdegen** [comment]
Is there a precedent for this? Do other orgs do it? In the case of something like Java it is baked in which is fine, but for python it adds a lot of verbosity without much in the way of informational content.

**Comment by dougiesquire** [comment]
Yeah, I'm not a huge fan of including ACCESS-NRI branding in package names. However, it could be helpful to have an agreed-upon way refer to ACCESS-NRI in "coding situations", e.g.:

- ANRI
- accessnri (this is what our [conda repo](https://anaconda.org/accessnri) is called)
- ACCESSNRI
- access_nri
- ACCESS_NRI
- ...

**Comment by headmetal** [comment]
I'm not aware of any precedent's for doing this either (nor am I personally a fan). I just know we (as in ACCESS-NRI collectively) are hoping to 'spread the good word' and promote our community contributions... and it would be nice if we had some way of unifying our works - but we can of course do this in other ways.

**Comment by headmetal** [comment]
> Yeah, I'm not a huge fan of including ACCESS-NRI branding in package names. However, it could be helpful to have an agreed-upon way refer to ACCESS-NRI in "coding situations", e.g.:
> 
> * ANRI
> * accessnri (this is what our [conda repo](https://anaconda.org/accessnri) is called)
> * ACCESSNRI
> * access_nri
> * ACCESS_NRI
> * ...

Can you give an example of a coding situation where you would do this? I'm guessing 'ACCESS_NRI' is closest to how its written everywhere else....

**Comment by rbeucher** [comment]
What would be great is a way to identify ACCESS-NRI code. Git gives us the option to see who has authored a line of code... Could we extend that to an organisation?

I agree with Dougie. We need to agree on a way to refer to ACCESS-NRI in docstrings, comments etc. I like to use ACCESS-NRI but I see how the hyphen would not play nice. In any case we need something explicit. ANRI is bad...short but bad....

**Comment by rbeucher** [comment]
I don't think we should add ACCESS-NRI to the package name. We should also be creative with our names... Cool names go a long way from my experience. In my past role we had Underworld, Badlands, Underware...

**Comment by rbeucher** [comment]
I have a created a Bot for the MED team called MEDOC...:-)

**Comment by dougiesquire** [comment]
Just noting that I recently found out that we also have an ACCESS-NRI readthedocs account called "accessnri", so there are now two examples of that in the wild

**Comment by dougiesquire** [comment]
> Can you give an example of a coding situation where you would do this? I'm guessing 'ACCESS_NRI' is closest to how its written everywhere else....

@headmetal, sorry, missed this. Examples might include the names of our conda and readthedocs accounts (both are "accessnri"), the name of the ACCESS-NRI catalog or any place where it's useful to have a ACCESS-NRI namespace

**Comment by aidanheerdegen** [comment]
The `-` vs `_` is, apparently, `kebab-case` vs `snake_case` (for searchability)

https://www.theserverside.com/definition/Kebab-case

I feel like we've done this already with the GitHub repo naming, though we don't have an issue for that, which came down on the `kebab-case`, but the above suggests `snake_case` is better for variables.

Package branding may overlap with use of a variable where a package name needs to be used to refer to code, e.g. python. In the case of `conda` the convention appears to use `kebab-case` for the package name, but the python package should use `snake-case`. Not sure why exactly, as it appears `conda` supports both as conda package names. 

https://docs.conda.io/projects/conda-build/en/stable/concepts/package-naming-conv.html

I'd probably plump for `access_nri` as a default. No space makes it difficult for those not in the know to understand what it might mean. Upper case will inevitably have to be made lower case for some uses, so it makes some sense to just adopt that as a standard for consistency.

**Comment by headmetal** [comment]
Updated [naming conventions](https://github.com/ACCESS-NRI/dev-docs/wiki/Code-guidelines#naming-conventions) to include [ACCESS-NRI organisation references](https://github.com/ACCESS-NRI/dev-docs/wiki/Code-guidelines#access-nri-organisation-references).
