### ISSUE TITLE
Python linters and formatters

### ISSUE THREAD

**Issue by SeanBryan51** [ACCESS-NRI/dev-docs#3]
What sort of linters and formatters do people use for python? Should we have a standard for these kind of tools too?

So far I've been using [Pylint](https://www.pylint.org/) for linting, [mypy](https://mypy-lang.org/) for static type checking and [autopep8](https://github.com/hhatto/autopep8) for code formatting (but I'm thinking I'd like to switch to [black](https://github.com/psf/black) for code formatting).

I haven't looked too much into alternative tools so I would be curious to hear what everyone is using.

**Comment by dougiesquire** [comment]
I use black and flake8 routinely. Have used mypy on some projects

**Comment by aidanheerdegen** [comment]
Yeah I've used `pep8` and `black` but have no strong opinions other than it is probably a good idea to decide on only one.

As to if it is a good idea to have it run automatically, well as @dougiesquire says that is mostly a matter of preference, and I don't think it is a good idea to require it. 

Having said which, you can have it in the CI, like `payu` does

https://github.com/payu-org/payu/pull/314#issuecomment-940529160

which at least flags when there are issues.

I think @SeanBryan51 is right, linting is good. Not used `mypy` but it looks cool.

I'd also like to extend linting to other languages where possible.

**Comment by headmetal** [comment]
I've used `black` previously too, happy with that.

Are you guys using it in your notebooks too? (for consistency)

**Comment by dougiesquire** [comment]
> Are you guys using it in your notebooks too? (for consistency)

Sometimes, e.g. if the notebook is getting included in docs. But I find the auto cell update quite annoying for using it all the time.

**Comment by headmetal** [comment]
Ok - for the guide lets stick with requesting people use `black` for linting *.py files - with 'auto-linting' and using black in notebooks as optional

**Comment by dougiesquire** [comment]
Pedantry perhaps, but I don't think `black` is a linter, it's code formatter. It might be good to include both a formatter and a linter (e.g. `flake8`, `pylint`) in the recommendations.

A very brief Google survey suggests `flake8` over `pylint`, but I have no strong preference.

**Comment by headmetal** [comment]
Yeah agreed, my bad - `black` is a formatter, you are right. Happy to include `flake8` as a linter in the guide

**Comment by headmetal** [comment]
Added draft '[Linting and formatting](https://github.com/ACCESS-NRI/dev-docs/wiki/Code-guidelines#linting-and-formatting)' section to guidelines.

**Comment by rbeucher** [comment]
Recommendations are fine. What we want is to enforce PEP8 convention.

**Comment by rbeucher** [comment]
However, if we want to include linting checks in our CI/CD we probably need to agree on tools.

**Comment by aidanheerdegen** [comment]
As it happens just came across [pre-commit.ci](https://pre-commit.ci) which touts itself as a free service to enable automatic linting and other checks using the [pre-commit framework](https://pre-commit.com).

"WOW!" I hear you say, "that looks peachy!".

It does eh? The context of noticing it was it failing for a mysterious reason in this PR

https://github.com/ncar-xdev/ecgtools/pull/148

Mysterious failures are not great for a largely automatic service over which you have little to no control. Any comments?

**Comment by harshula** [comment]
Have a look at the [Ruff linter](https://beta.ruff.rs/docs/) for CI

**Comment by headmetal** [comment]
Closing as guidelines updated as per [this comment above](https://github.com/ACCESS-NRI/dev-docs/issues/3#issuecomment-1522609874).

Automated linting and CI/CD discussion moved to new issue [here](https://github.com/ACCESS-NRI/dev-docs/issues/8)

**Comment by dougiesquire** [comment]
I'm recently moved to `ruff` over `flake8` and so far so good. It also has `pyproject.toml` support. Issues about adding `pyproject.toml` support to `flake8` were closed as they got too heated, so it's unlikely to be something that's supported soon.

If I'm still happy with `ruff` in a few weeks and there have been no objections here, I'll update the wiki to recommend `ruff` over `flake8`
