### ISSUE TITLE
Python: Convention for exposed and non_exposed function / methods

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/dev-docs#4]
@headmetal Not sure you put that in the document but I propose we prepend the functions/methods names with an underscore to represent "private" or parts that are not exposed to the users.

**Comment by headmetal** [comment]
Added to [Code Guidelines > Python > Private functions/methods](https://github.com/ACCESS-NRI/dev-docs/wiki/Code-guidelines#private-functionsmethods).
