### ISSUE TITLE
Github Action for publishing conda packages

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/dev-docs#6]
It would be good to settle on a preferred approach for publishing packages to conda in CI. There're a number of relevant Github Actions that exist:

- https://github.com/marketplace/actions/build-and-publish-conda-packages-to-anaconda-org
- https://github.com/marketplace/actions/publish-conda-package-action
- https://github.com/marketplace/actions/publish-conda-package-to-anaconda-org
- https://github.com/marketplace/actions/build-and-upload-conda-packages

Some discussion is happening here: https://forum.access-hive.org.au/t/favourite-github-action-for-building-publishing-a-conda-package/747

**Comment by dougiesquire** [comment]
I’ve ended up using this action:

https://github.com/marketplace/actions/build-and-upload-conda-packages

with no better justification than that it’s well documented and a little more flexible with dependencies than some of the other options. It looks like it also has the option to publish to different labels, but I haven’t tried using that.

As an example of usage, [this workflow](https://github.com/ACCESS-NRI/intake-dataframe-catalog/blob/main/.github/workflows/cd.yml) builds and uploads the PyPI dist and then builds and uploads the conda dist from the PyPI dist.

**Comment by aidanheerdegen** [comment]
I reckon add something to the wiki to this effect and consider this closed. Should include some brief guidelines for creating the publishing tokens. Happy to contribute if required.

**Comment by dougiesquire** [comment]
I've added a section on CI/CD that lists some recommended Actions and gives examples of their use. Feel free to to edit however you like

https://github.com/ACCESS-NRI/dev-docs/wiki/Continuous-integration-and-deployment
